name: Release

on:
  push:
    branches:
      - master
    tags:
      - v/*

jobs:
    build-linux:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.21.3'

        - name: Build
          run: go build -v -o ./build/sandwich-delivery-linux-amd64 ./src/main

        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            name: sandwich-delivery-linux-amd64
            path: ./build/sandwich-delivery-linux-amd64

    build-windows:
        runs-on: windows-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.21.3'

        - name: Build
          run: go build -v -o ./build/sandwich-delivery-windows-amd64.exe ./src/main

        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            name: sandwich-delivery-windows-amd64.exe
            path: ./build/sandwich-delivery-windows-amd64.exe

    publish:
      needs: [build-linux, build-windows]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Download Linux
          uses: actions/download-artifact@v2
          with:
            name: sandwich-delivery-linux-amd64
            path: ./files

        - name: Download Windows
          uses: actions/download-artifact@v2
          with:
            name: sandwich-delivery-windows-amd64.exe
            path: ./files

        - name: Create Release
          if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
          uses: softprops/action-gh-release@v1
          with:
              files: |
                ./files/sandwich-delivery-linux-amd64
                ./files/sandwich-delivery-windows-amd64.exe
              tag_name: ${{ github.ref }}
              body: |
                # Changelog
                ${{ github.event.release.body }}
                
                This is an automated draft release.
              draft: true
              prerelease: ${{ contains(github.ref, 'pre') || contains(github.ref, 'prerelease') }}
